### ISSUE TITLE
Segmentation fault with release executable 

### ISSUE THREAD

**Issue by gouvinb** [ajalt/clikt#447] opened 2023-08-30 15:36 UTC
# Description

Here is my example file:

```kotlin
import com.github.ajalt.clikt.core.CliktCommand
import com.github.ajalt.clikt.core.subcommands


class SampleSubCommand() : CliktCommand("help", "epilog", "name") {
    override fun run() {}
}

class App : CliktCommand(name = NAME) {
    private val sampleSubCommand = SampleSubCommand()

    init {
        subcommands(
            sampleSubCommand,
        )
    }

    override fun run() {}

    companion object {
        const val NAME = "playground"
    }
}


fun main(args: Array<String>) {
    App().main(args)
}
```

In this example, I add an example subcommand to my program.

## Actual result

* Build this example for linuxX64 target
* Run the output in Linux (I'm on arch)
* See the `segmentation fault (core dumped)`.

## More information

The `segmentation fault` only occurs in release version **with** the `subcommands` called. I don't have this problem with a debug build.

## Log

There is no log.

**Comment by ajalt** [comment] 2023-08-30 16:29
I imagine this is related to Arch. Can you try on a more common distro to see if the same thing happens?

**Comment by gouvinb** [comment] 2023-08-30 17:39
It's the same in an ubuntu 23.04 VM (with kernel 6.2.0-generic)

**Comment by Jeansen** [comment] 2023-09-11 20:15
Got the same. But it seems to have to do with Kotlin 9.

This code with version 4.0.0 of Clikt works fine if I compile it against Kotlin 1.8.20 but gives me a segmentation fault in 1.9.0:

```
import com.github.ajalt.clikt.completion.CompletionCommand
import com.github.ajalt.clikt.core.CliktCommand
import com.github.ajalt.clikt.core.subcommands

class K8s : CliktCommand() {
    init {
        subcommands(
            CompletionCommand(),

            )

    }

    override fun run() = Unit
}

fun main(args: Array<String>) {
    K8s().main(args)
}

```

**Comment by michael-taylor** [comment] 2023-09-22 06:00
I'm getting what I believe is the same thing on Windows with Kotlin-native 1.9.0.  In the debug build, the "--help" text works fine, but in the release build, "--help" doesn't print out anything.

**Comment by ajalt** [comment] 2023-09-25 18:07
Thank you to everyone who's helped reproduce this. Based on @DLochmelis33's valgrind output, I was able to confirm that this is caused by the JetBrains markdown library. I've filed https://github.com/JetBrains/markdown/issues/130.

The only workaround I can think of on Clikt's end would be to add a configuration flag to disable markdown parsing entirely.

**Comment by Jeansen** [comment] 2023-09-25 21:25
Well, I think it could not harm to have such a flag. At least, then - in the future and until the issue is fixed on JB's side - one would have some more control. Of course, the root cause still is that there's something wrong with the Markdown parser.

**Comment by ajalt** [comment] 2023-10-02 19:34
4.2.1 has been released which should resolve this issue. Thanks to everyone who gave feedback!

**Closed by ajalt** 2023-10-02 19:34 UTC
