### ISSUE TITLE
support newline in @argfile

### ISSUE THREAD

**Issue by cvmocanu** [ajalt/clikt#247] opened 2020-11-10 19:34 UTC
Currently newlines are not supported in ``@argfiles``.

In my current project, I am using picocli which supports this.
One of the reasons I am using an ``@argfile`` is that I can pass arguments containing newlines.

I was looking to use clikt instead of picocli, hoping for improved performance (for my project, picocli takes 300ms to parse the command line which is very excessive).

Please support newlines in ``@argfile``.
Such newlines should be supported just as in the terminal: if we are inside single or double quotes, any newline becomes part of the value.

Looking at the source code it seems to me you worked hard to prevent this feature (by forbidding us to backslash-escape the newline) and I don't really understand why...

**Comment by ajalt** [comment] 2020-11-10 21:21
duplicate of #248

**Closed by ajalt** 2020-11-10 21:21 UTC

**Comment by cvmocanu** [comment] 2020-11-10 21:22
Sorry for creating duplicates.
I had some issue with the browser (back button and stuff) and I didn't notice that I already created a ticket.
