### ISSUE TITLE
Support for "optional flag"

### ISSUE THREAD

**Issue by zeldigas** [ajalt/clikt#329] opened 2022-01-09 08:59 UTC
Right now `flag` option is not null. While this works fine for many scenarios, there are some use cases when this is not desirable. For example when we have a mix of command line options that should fallback to values in some configuration file (and value source is not an option due varios reasons, like the fact that location of this configuration file depends on another cli option).

It would be great to have ability for having a flag with 3 states - true, fase, null. `null` will be the marker that user did not specify any option, while `true` and `false` will tell that either main or alternative option was specified

Simplest solution that I can image is to have one more function:
```kotlin
fun RawOption.optionalFlag(vararg secondaryNames:String): FlagOption<Boolean?> {
    return FlagOption(
        names = names,
        secondaryNames = secondaryNames.toSet(),
        optionHelp = optionHelp,
        hidden = hidden,
        helpTags = helpTags,
        valueSourceKey = valueSourceKey,
        envvar = envvar,
        transformEnvvar = {
            when (it.lowercase()) {
                "true", "t", "1", "yes", "y", "on" -> true
                "false", "f", "0", "no", "n", "off" -> false
                else -> throw BadParameterValue(context.localization.boolConversionError(it), this)
            }
        },
        transformAll = {
            if (it.isEmpty()) null else it.last() !in secondaryNames  // <---------- here is the main change, returning null and not default
        },
        validator = {}
    )
}
```

**Comment by ajalt** [comment] 2022-01-09 17:40
Thanks for the issue. This is a duplicate of #309. That issue has examples of how to implement this now, and the [4.0 branch][1] has this built in.

[1]:https://github.com/ajalt/clikt/blob/7b1c3dc5aacfbd07b6536dd03a3dcaa2b2cdda87/clikt/src/commonMain/kotlin/com/github/ajalt/clikt/parameters/types/boolean.kt

**Closed by ajalt** 2022-01-09 17:40 UTC
