### ISSUE TITLE
Kotlin-Native charset error on Windows

### ISSUE THREAD

**Issue by tothlp** [ajalt/clikt#525] opened 2024-07-03 17:57 UTC
I try reading an argument, like the following:
```kotlin
private val task by argument(help = "Name of the task")
```

When I use Hungarian accented characters like űáéúő on macOS and Linux, everything is fine. When I do the same on Windows, these characters are replaced by ?, or a rotated square with a question mark. I tried playing with the character encoding, but I found nothing, which is compatible with Kotlin Native.

**Comment by ajalt** [comment] 2024-07-03 18:05
Is this an issue with Clikt? Did you try a plain `println("űáéúő")`?

**Comment by tothlp** [comment] 2024-07-04 08:27
When I run `println("űáéúő")`, it prints well. As soon as I try to print the task argument, it prints the gibberish. I am not sure anymore, if that's an issue with Clikt, to be honest. But I have no other ideas. Can you maybe suggest, where to look next? Thanks!

**Comment by tothlp** [comment] 2024-07-04 09:01
Also, if I simply print the arguments:

```kotlin
fun main(args: Array<String>) = App().main(args).also {
	println("args: ${args.joinToString()}")
}
```

It also prints the incorrect characters. Now I'm sure that is not an issue with Clikt. Happy for you, bad for me. :(

**Comment by ajalt** [comment] 2024-07-05 15:54
Thanks for clarifying. I'll close this issue since it's not caused by clikt, but if you do find the solution, feel free to post it here for anyone who might encounter the same thing in the future.

**Closed by ajalt** 2024-07-05 15:54 UTC
